"""
MicroQuant-ESP32: C++ Header Generator for Embedded Flash DROM & SRAM
Exports compressed tensors to C/C++ header files with PROGMEM/const qualifiers.
"""

import os
import numpy as np
from typing import Dict, Any, List

class Exporter:
    @staticmethod
    def generate_cpp_header(tensor_name: str,
                             quant_type: str,
                             packed_data: np.ndarray,
                             scale: float,
                             original_shape: List[int],
                             output_path: str,
                             namespace: str = "MicroQuantModel") -> str:
        """
        Generates a standalone C++ header file.
        """
        flat_data = packed_data.flatten()
        num_bytes = len(flat_data)
        shape_str = ", ".join(str(s) for s in original_shape)
        
        lines = []
        lines.append("// ===================================================================")
        lines.append(f"// Auto-generated by MicroQuant-ESP32 Compression Engine")
        lines.append(f"// Tensor: {tensor_name} | Format: {quant_type.upper()} | Packed: {num_bytes} Bytes")
        lines.append(f"// Original Shape: [{shape_str}] | Scale/Gamma: {scale:.8f}f")
        lines.append("// ===================================================================")
        lines.append("#pragma once")
        lines.append("#include <stdint.h>")
        lines.append("")
        lines.append(f"namespace {namespace} {{")
        lines.append("")
        lines.append(f"// Quantization metadata")
        lines.append(f"constexpr const char* {tensor_name.upper()}_QUANT_TYPE = \"{quant_type}\";")
        lines.append(f"constexpr uint32_t {tensor_name.upper()}_BYTES = {num_bytes};")
        lines.append(f"constexpr float {tensor_name.upper()}_SCALE = {scale:.8f}f;")
        
        for idx, s in enumerate(original_shape):
            lines.append(f"constexpr uint32_t {tensor_name.upper()}_DIM_{idx} = {s};")
            
        lines.append("")
        lines.append(f"// Packed weight matrix stored directly in Flash DROM (Zero-Copy Read)")
        if quant_type == "int8":
            lines.append(f"const int8_t {tensor_name.upper()}_DATA[{num_bytes}] = {{")
            # Format as signed hex/decimal
            chunk_size = 16
            for i in range(0, num_bytes, chunk_size):
                chunk = flat_data[i:i+chunk_size]
                chunk_str = ", ".join(f"{int(val):4d}" for val in chunk)
                lines.append(f"    {chunk_str},")
            lines.append("};")
        else:
            lines.append(f"const uint8_t {tensor_name.upper()}_DATA[{num_bytes}] = {{")
            chunk_size = 16
            for i in range(0, num_bytes, chunk_size):
                chunk = flat_data[i:i+chunk_size]
                chunk_str = ", ".join(f"0x{int(val):02X}" for val in chunk)
                lines.append(f"    {chunk_str},")
            lines.append("};")
            
        lines.append("")
        lines.append(f"}} // namespace {namespace}")
        
        header_content = "\n".join(lines) + "\n"
        
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(header_content)
            
        return header_content

    @staticmethod
    def generate_cpp_header_int4_groupwise(tensor_name: str,
                                           packed_data: np.ndarray,
                                           group_scales: np.ndarray,
                                           original_shape: List[int],
                                           output_path: str,
                                           group_size: int = 32,
                                           namespace: str = "MicroQuantModel") -> str:
        """
        Generates a standalone C++ header file for Group-wise INT4 weights & scales.
        """
        flat_data = packed_data.flatten()
        flat_scales = group_scales.flatten()
        num_bytes = len(flat_data)
        num_scales = len(flat_scales)
        shape_str = ", ".join(str(s) for s in original_shape)
        
        lines = []
        lines.append("// ===================================================================")
        lines.append("// Auto-generated by MicroQuant-ESP32 Compression Engine")
        lines.append(f"// Tensor: {tensor_name} | Format: INT4-GROUP{group_size} | Packed: {num_bytes} Bytes")
        lines.append(f"// Original Shape: [{shape_str}] | Num Group Scales: {num_scales}")
        lines.append("// ===================================================================")
        lines.append("#pragma once")
        lines.append("#include <stdint.h>")
        lines.append("")
        lines.append(f"namespace {namespace} {{")
        lines.append("")
        lines.append(f"constexpr const char* {tensor_name.upper()}_QUANT_TYPE = \"int4_group{group_size}\";")
        lines.append(f"constexpr uint32_t {tensor_name.upper()}_BYTES = {num_bytes};")
        lines.append(f"constexpr uint32_t {tensor_name.upper()}_NUM_SCALES = {num_scales};")
        lines.append(f"constexpr uint32_t {tensor_name.upper()}_GROUP_SIZE = {group_size};")
        
        for idx, s in enumerate(original_shape):
            lines.append(f"constexpr uint32_t {tensor_name.upper()}_DIM_{idx} = {s};")
            
        lines.append("")
        lines.append(f"// Packed INT4 nibble weights in Flash DROM")
        lines.append(f"const uint8_t {tensor_name.upper()}_DATA[{num_bytes}] = {{")
        chunk_size = 16
        for i in range(0, num_bytes, chunk_size):
            chunk = flat_data[i:i+chunk_size]
            chunk_str = ", ".join(f"0x{int(val):02X}" for val in chunk)
            lines.append(f"    {chunk_str},")
        lines.append("};")
        lines.append("")
        
        lines.append(f"// Group scale factors in Flash DROM")
        lines.append(f"const float {tensor_name.upper()}_GROUP_SCALES[{num_scales}] = {{")
        chunk_size = 8
        for i in range(0, num_scales, chunk_size):
            chunk = flat_scales[i:i+chunk_size]
            chunk_str = ", ".join(f"{float(val):.8e}f" for val in chunk)
            lines.append(f"    {chunk_str},")
        lines.append("};")
        
        lines.append("")
        lines.append(f"}} // namespace {namespace}")
        
        header_content = "\n".join(lines) + "\n"
        os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(header_content)
            
        return header_content

